---
# defaults file for deploy-python

# the default directory to upload the python pax file to
python_pax_dir: /tmp

# the default python file name
python_file_name: python-3.8.3

# the space required for the temporary pax file or unpacked files
# (if both are in the same file system, this will be doubled)
python_space: 250000
