---
# defaults file for deploy-python

# the default python file name
python_file_name: python-3.8.3

# the temporary directory to copy the pax file to
python_pax_dir: /tmp/python/pax
# the root directory to unpack the files for install
python_install_dir: /
# the underlying filesystem that python will unpack to
python_install_fs: /usr/lpp/IBM

python_install_dirs:
  - "{{ python_pax_dir }}"
  - "{{ python_install_fs }}"

# the space required for the temporary pax file or unpacked files
# (if both are in the same file system, this will be doubled)
python_space: 250000

# the path to sftp on Ansible host
sftp_path: /usr/bin/sftp {{ansible_sftp_extra_args}}
