---
# defaults file for deploy-rocket
profile_text: |
  export _BPXK_AUTOCVT="ON"
  export ZOAU=/usr/lpp/IBM/zoau/v1r1m0
  export PYZ=/usr/lpp/IBM/cyp/v3r8/pyz
  export ROCKET=/usr/lpp/Rocket
  export ZOAU_HOME="${ZOAU}"
  export PYTHONPATH="${ZOAU}/lib"
  export LIBPATH="${ZOAU}/lib:${PYZ}/lib:/lib:/usr/lib:."
  export PATH="${HOME}/bin:${ZOAU}/bin:${PYZ}/bin:${ROCKET}/bin:/bin:/var/bin"
  export _CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  export _TAG_REDIR_ERR="txt"
  export _TAG_REDIR_IN="txt"
  export _TAG_REDIR_OUT="txt"
  export LANG="C"
  export GIT_SHELL=${ROCKET}/bin/bash
  export GIT_EXEC_PATH=${ROCKET}/libexec/git-core
  export GIT_TEMPLATE_DIR=${ROCKET}/share/git-core/templates
  git config --global core.editor "/bin/vi -W filecodeset=ISO8859-1" 
  git config --global user.name "Mike Fulton"
  git config --global user.email mikefultonpersonal@gmail.com

  export TERM=xterm
  set -o emacs
