---
# defaults file for deploy-rocket

# the default directory to upload the rocket pax file to
rocket_pax_dir: /tmp

# the default rocket file names
gzip_file_name: gzip-1.6-edc_b0005.160229
unzip_file_name: unzip-6.0_b0006.161123
bash_file_name: bash-4.3_b018.170518
git_file_name: git-2.14.4_b11.190917

# the space required for the temporary zip/tar files or unpacked files
# (if both are in the same file system, this will be doubled)
rocket_space: 10000
